# Setup
name:         Paul Chilton
tagline:      Electronics, Home Automation, IT & More

# Leave blank
baseurl:      ""

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
repository: "paulchilton/paulchilton"

siteurl: "https://paulchilton.github.io"